### PR TITLE
fix: not link wayland-client in opensuse

### PR DESCRIPTION
**Pull request by wineee**
log: just use pkgconfig to find

### CODE REVIEW

**Comment by wineee** [comment]
@hillwoodroc 这个确认可用吗

**Comment by hillwoodroc** [comment]
[fix-library-links.patch.txt](https://github.com/linuxdeepin/treeland/files/14955025/fix-library-links.patch.txt)
treeland-helper 还有一处要改。

**Comment by wineee** [comment]
> [fix-library-links.patch.txt](https://github.com/linuxdeepin/treeland/files/14955025/fix-library-links.patch.txt) treeland-helper 还有一处要改。

改了

**Review by justforlxz — APPROVED** [review]

**Pull request merged**
